"""initial schema

Revision ID: 4b58c2e3ae59
Revises: 
Create Date: 2026-09-09 10:44:11.501196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4b58c2e3ae59'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36, collation='utf8mb4_bin').with_variant(sa.String(length=36, collation='utf8mb4_bin'), 'mysql'), nullable=False),
    sa.Column('actor_principal_id', sa.String(length=36, collation='utf8mb4_bin').with_variant(sa.String(length=36, collation='utf8mb4_bin'), 'mysql'), nullable=False),
    sa.Column('actor_type', sa.String(length=8, collation='ascii_bin'), nullable=False),
    sa.Column('auth_method', sa.String(length=8, collation='ascii_bin'), nullable=False),
    sa.Column('action', sa.String(length=64, collation='ascii_bin'), nullable=False),
    sa.Column('target_type', sa.String(length=32, collation='ascii_bin'), nullable=False),
    sa.Column('target_id', sa.String(length=191, collation='utf8mb4_bin'), nullable=False),
    sa.Column('before_summary', sa.JSON(), nullable=True),
    sa.Column('after_summary', sa.JSON(), nullable=True),
    sa.Column('reason', sa.String(length=500, collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('trace_id', sa.String(length=36, collation='utf8mb4_bin').with_variant(sa.String(length=36, collation='utf8mb4_bin'), 'mysql'), nullable=False),
    sa.Column('operation_id', sa.String(length=36, collation='utf8mb4_bin').with_variant(sa.String(length=36, collation='utf8mb4_bin'), 'mysql'), nullable=True),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_target', 'audit_events', ['target_type', 'target_id', 'created_at'], unique=False)
    op.create_table('authorization_guard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('revision', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('principals',
    sa.Column('id', sa.String(length=36, collation='utf8mb4_bin').with_variant(sa.String(length=36, collation='utf8mb4_bin'), 'mysql'), nullable=False),
    sa.Column('type', sa.String(length=8, collation='ascii_bin'), nullable=False),
    sa.Column('display_name', sa.String(length=200, collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.CheckConstraint("type IN ('human','service')", name='ck_principals_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quota_usage',
    sa.Column('scope', sa.String(length=8, collation='ascii_bin'), nullable=False),
    sa.Column('owner_id', sa.String(length=36, collation='utf8mb4_bin').with_variant(sa.String(length=36, collation='utf8mb4_bin'), 'mysql'), nullable=False),
    sa.Column('used_bytes', sa.BigInteger(), nullable=False),
    sa.Column('reserved_bytes', sa.BigInteger(), nullable=False),
    sa.Column('dashboard_count', sa.Integer(), nullable=False),
    sa.Column('reserved_count', sa.Integer(), nullable=False),
    sa.CheckConstraint("scope IN ('owner','global')", name='ck_quota_scope'),
    sa.CheckConstraint('used_bytes >= 0 AND reserved_bytes >= 0', name='ck_quota_bytes'),
    sa.PrimaryKeyConstraint('scope', 'owner_id')
    )
    op.create_table('upload_reservations',
    sa.Column('operation_id', sa.String(length=36, collation='utf8mb4_bin').with_variant(sa.String(length=36, collation='utf8mb4_bin'), 'mysql'), nullable=False),
    sa.Column('attempt_id', sa.String(length=36, collation='utf8mb4_bin').with_variant(sa.String(length=36, collation='utf8mb4_bin'), 'mysql'), nullable=False),
    sa.Column('owner_id', sa.String(length=36, collation='utf8mb4_bin').with_variant(sa.String(length=36, collation='utf8mb4_bin'), 'mysql'), nullable=False),
    sa.Column('reserved_bytes', sa.BigInteger(), nullable=False),
    sa.Column('reserved_count', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.PrimaryKeyConstraint('operation_id')
    )
    op.create_index('ix_reservations_expiry', 'upload_reservations', ['expires_at'], unique=False)
    op.create_table('dashboards',
    sa.Column('id', sa.String(length=36, collation='utf8mb4_bin').with_variant(sa.String(length=36, collation='utf8mb4_bin'), 'mysql'), nullable=False),
    sa.Column('owner_principal_id', sa.String(length=36, collation='utf8mb4_bin').with_variant(sa.String(length=36, collation='utf8mb4_bin'), 'mysql'), nullable=False),
    sa.Column('title', sa.String(length=200, collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('description', sa.String(length=2000, collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('current_version_id', sa.String(length=36, collation='utf8mb4_bin').with_variant(sa.String(length=36, collation='utf8mb4_bin'), 'mysql'), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16, collation='ascii_bin'), nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('published_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.CheckConstraint("status IN ('published','archived')", name='ck_dashboards_status'),
    sa.CheckConstraint('revision >= 1', name='ck_dashboards_revision'),
    sa.ForeignKeyConstraint(['owner_principal_id'], ['principals.id'], name='fk_dashboards_owner'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dashboards_owner_status_updated', 'dashboards', ['owner_principal_id', 'status', 'updated_at', 'id'], unique=False)
    op.create_index('ix_dashboards_updated', 'dashboards', ['updated_at', 'id'], unique=False)
    op.create_table('groups',
    sa.Column('id', sa.String(length=36, collation='utf8mb4_bin').with_variant(sa.String(length=36, collation='utf8mb4_bin'), 'mysql'), nullable=False),
    sa.Column('display_name', sa.String(length=200, collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('owner_principal_id', sa.String(length=36, collation='utf8mb4_bin').with_variant(sa.String(length=36, collation='utf8mb4_bin'), 'mysql'), nullable=False),
    sa.Column('source', sa.String(length=16, collation='ascii_bin'), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.CheckConstraint("source = 'local'", name='ck_groups_local'),
    sa.ForeignKeyConstraint(['owner_principal_id'], ['principals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('identity_links',
    sa.Column('issuer', sa.String(length=191, collation='utf8mb4_bin'), nullable=False),
    sa.Column('enterprise_user_id', sa.String(length=191, collation='utf8mb4_bin'), nullable=False),
    sa.Column('principal_id', sa.String(length=36, collation='utf8mb4_bin').with_variant(sa.String(length=36, collation='utf8mb4_bin'), 'mysql'), nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.ForeignKeyConstraint(['principal_id'], ['principals.id'], ),
    sa.PrimaryKeyConstraint('issuer', 'enterprise_user_id')
    )
    op.create_table('operations',
    sa.Column('id', sa.String(length=36, collation='utf8mb4_bin').with_variant(sa.String(length=36, collation='utf8mb4_bin'), 'mysql'), nullable=False),
    sa.Column('principal_id', sa.String(length=36, collation='utf8mb4_bin').with_variant(sa.String(length=36, collation='utf8mb4_bin'), 'mysql'), nullable=False),
    sa.Column('idempotency_key', sa.String(length=36, collation='ascii_bin'), nullable=False),
    sa.Column('action', sa.String(length=64, collation='ascii_bin'), nullable=False),
    sa.Column('method', sa.String(length=8, collation='ascii_bin'), nullable=False),
    sa.Column('path', sa.String(length=256, collation='ascii_bin'), nullable=False),
    sa.Column('target_id', sa.String(length=36, collation='utf8mb4_bin').with_variant(sa.String(length=36, collation='utf8mb4_bin'), 'mysql'), nullable=True),
    sa.Column('request_hash', sa.String(length=64, collation='ascii_bin'), nullable=False),
    sa.Column('state', sa.String(length=16, collation='ascii_bin'), nullable=False),
    sa.Column('attempt_id', sa.String(length=36, collation='utf8mb4_bin').with_variant(sa.String(length=36, collation='utf8mb4_bin'), 'mysql'), nullable=False),
    sa.Column('lease_until', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.JSON(), nullable=True),
    sa.Column('result_expires_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('result_purged_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=True),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.CheckConstraint("state IN ('accepted','processing','succeeded','failed')", name='ck_operations_state'),
    sa.ForeignKeyConstraint(['principal_id'], ['principals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('principal_id', 'idempotency_key', name='uq_operations_principal_key')
    )
    op.create_index('ix_operations_principal_created', 'operations', ['principal_id', 'created_at'], unique=False)
    op.create_index('ix_operations_state_lease', 'operations', ['state', 'lease_until'], unique=False)
    op.create_table('service_accounts',
    sa.Column('principal_id', sa.String(length=36, collation='utf8mb4_bin').with_variant(sa.String(length=36, collation='utf8mb4_bin'), 'mysql'), nullable=False),
    sa.Column('name', sa.String(length=200, collation='utf8mb4_bin'), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.CheckConstraint('JSON_VALID(scopes)', name='ck_service_accounts_scopes_json'),
    sa.ForeignKeyConstraint(['principal_id'], ['principals.id'], ),
    sa.PrimaryKeyConstraint('principal_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('dashboard_grants',
    sa.Column('dashboard_id', sa.String(length=36, collation='utf8mb4_bin').with_variant(sa.String(length=36, collation='utf8mb4_bin'), 'mysql'), nullable=False),
    sa.Column('subject_type', sa.String(length=20, collation='ascii_bin'), nullable=False),
    sa.Column('subject_id', sa.String(length=191, collation='utf8mb4_bin'), nullable=False),
    sa.Column('role', sa.String(length=8, collation='ascii_bin'), nullable=False),
    sa.Column('starts_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=True),
    sa.Column('expires_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=True),
    sa.Column('created_by', sa.String(length=36, collation='utf8mb4_bin').with_variant(sa.String(length=36, collation='utf8mb4_bin'), 'mysql'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.CheckConstraint("role IN ('viewer','editor')", name='ck_grants_role'),
    sa.CheckConstraint('starts_at IS NULL OR expires_at IS NULL OR starts_at < expires_at', name='ck_grants_window'),
    sa.ForeignKeyConstraint(['created_by'], ['principals.id'], ),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], ),
    sa.PrimaryKeyConstraint('dashboard_id', 'subject_type', 'subject_id')
    )
    op.create_index('ix_grants_subject', 'dashboard_grants', ['subject_type', 'subject_id'], unique=False)
    op.create_table('dashboard_versions',
    sa.Column('id', sa.String(length=36, collation='utf8mb4_bin').with_variant(sa.String(length=36, collation='utf8mb4_bin'), 'mysql'), nullable=False),
    sa.Column('dashboard_id', sa.String(length=36, collation='utf8mb4_bin').with_variant(sa.String(length=36, collation='utf8mb4_bin'), 'mysql'), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.String(length=64, collation='ascii_bin'), nullable=False),
    sa.Column('sha256', sa.String(length=64, collation='ascii_bin'), nullable=False),
    sa.Column('byte_size', sa.BigInteger(), nullable=False),
    sa.Column('created_by', sa.String(length=36, collation='utf8mb4_bin').with_variant(sa.String(length=36, collation='utf8mb4_bin'), 'mysql'), nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['principals.id'], ),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dashboard_id', 'id', name='uq_versions_dashboard_id'),
    sa.UniqueConstraint('dashboard_id', 'number', name='uq_versions_dashboard_number'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index('ix_versions_dashboard_created', 'dashboard_versions', ['dashboard_id', 'created_at'], unique=False)
    op.create_table('group_members',
    sa.Column('group_id', sa.String(length=36, collation='utf8mb4_bin').with_variant(sa.String(length=36, collation='utf8mb4_bin'), 'mysql'), nullable=False),
    sa.Column('human_principal_id', sa.String(length=36, collation='utf8mb4_bin').with_variant(sa.String(length=36, collation='utf8mb4_bin'), 'mysql'), nullable=False),
    sa.Column('added_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['human_principal_id'], ['principals.id'], ),
    sa.PrimaryKeyConstraint('group_id', 'human_principal_id')
    )
    op.create_table('view_capabilities',
    sa.Column('token_digest', sa.String(length=64, collation='ascii_bin'), nullable=False),
    sa.Column('human_principal_id', sa.String(length=36, collation='utf8mb4_bin').with_variant(sa.String(length=36, collation='utf8mb4_bin'), 'mysql'), nullable=False),
    sa.Column('identity_session_ref', sa.String(length=191, collation='utf8mb4_bin'), nullable=True),
    sa.Column('session_version', sa.BigInteger(), nullable=True),
    sa.Column('dashboard_id', sa.String(length=36, collation='utf8mb4_bin').with_variant(sa.String(length=36, collation='utf8mb4_bin'), 'mysql'), nullable=False),
    sa.Column('version_id', sa.String(length=36, collation='utf8mb4_bin').with_variant(sa.String(length=36, collation='utf8mb4_bin'), 'mysql'), nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('expires_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], ),
    sa.ForeignKeyConstraint(['human_principal_id'], ['principals.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['dashboard_versions.id'], ),
    sa.PrimaryKeyConstraint('token_digest')
    )
    op.create_index('ix_view_capabilities_expiry', 'view_capabilities', ['expires_at'], unique=False)
    # ### end Alembic commands ###

    # Two-step composite FK: dashboards.current_version_id must reference a
    # version belonging to the same dashboard (contracts.md §8). Added after
    # both tables exist to avoid the circular dependency.
    op.create_foreign_key(
        "fk_dashboards_current_version",
        "dashboards", "dashboard_versions",
        ["id", "current_version_id"], ["dashboard_id", "id"],
        ondelete="RESTRICT")

    # Seed the shared authorization-change coordination row.
    op.execute("INSERT INTO authorization_guard (id, revision) VALUES (1, 1)")


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint("fk_dashboards_current_version", "dashboards", type_="foreignkey")
    op.drop_constraint("fk_dashboards_owner", "dashboards", type_="foreignkey")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_view_capabilities_expiry', table_name='view_capabilities')
    op.drop_table('view_capabilities')
    op.drop_table('group_members')
    op.drop_index('ix_versions_dashboard_created', table_name='dashboard_versions')
    op.drop_table('dashboard_versions')
    op.drop_index('ix_grants_subject', table_name='dashboard_grants')
    op.drop_table('dashboard_grants')
    op.drop_table('service_accounts')
    op.drop_index('ix_operations_state_lease', table_name='operations')
    op.drop_index('ix_operations_principal_created', table_name='operations')
    op.drop_table('operations')
    op.drop_table('identity_links')
    op.drop_table('groups')
    op.drop_index('ix_dashboards_updated', table_name='dashboards')
    op.drop_index('ix_dashboards_owner_status_updated', table_name='dashboards')
    op.drop_table('dashboards')
    op.drop_index('ix_reservations_expiry', table_name='upload_reservations')
    op.drop_table('upload_reservations')
    op.drop_table('quota_usage')
    op.drop_table('principals')
    op.drop_table('authorization_guard')
    op.drop_index('ix_audit_target', table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
