;(async () => {
  "use strict"
  // Trusted loader: the capability is read from the fragment and cleared
  // immediately; the only credential kept lives in this closure's memory.
  let capability = location.hash.slice(1)
  history.replaceState(null, "", location.pathname)
  const status = document.getElementById("render-status")
  const controlOrigin = document.querySelector(
    'meta[name="x-dashboard-control-origin"]',
  )?.content
  const dashboardId = document.querySelector('meta[name="x-dashboard-id"]')?.content
  function fail() {
    capability = ""
    status.setAttribute("role", "alert")
    status.replaceChildren(
      "内容无法加载，访问权限可能已失效或已过期。",
      document.createElement("br"),
    )
    if (controlOrigin && dashboardId) {
      const back = document.createElement("a")
      back.href = `${controlOrigin}/dashboards/${dashboardId}`
      back.textContent = "返回看板入口重新授权"
      back.rel = "noopener"
      status.append(back)
    } else {
      // No positional information: never guess a dashboard or permission.
      status.append("请从看板链接重新进入。")
    }
  }
  try {
    if (
      !capability ||
      capability.length > 4096 ||
      /[\s\r\n]/.test(capability)
    ) {
      throw new Error("invalid-capability")
    }
    const response = await fetch("/content", {
      headers: { Authorization: `Bearer ${capability}` },
      credentials: "omit",
      cache: "no-store",
      redirect: "error",
      referrerPolicy: "no-referrer",
      signal: AbortSignal.timeout(30000),
    })
    capability = ""
    if (
      !response.ok ||
      !/^text\/plain(?:;|$)/i.test(response.headers.get("content-type") || "")
    ) {
      throw new Error("content-unavailable")
    }
    const html = await response.text()
    const frame = document.createElement("iframe")
    frame.id = "dashboard-content"
    frame.title = "已发布的看板内容"
    frame.setAttribute("sandbox", "allow-scripts")
    frame.setAttribute("referrerpolicy", "no-referrer")
    // This policy precedes all generated bytes. Further CSP policies in the
    // document can only restrict it. The iframe enforces the opaque origin.
    const policy =
      "default-src 'none'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; img-src data: blob:; font-src data:; media-src 'none'; connect-src 'none'; frame-src 'none'; object-src 'none'; worker-src 'none'; base-uri 'none'; form-action 'none'"
    frame.srcdoc = `<!doctype html><meta http-equiv="Content-Security-Policy" content="${policy}"><meta name="referrer" content="no-referrer">${html}`
    document.body.append(frame)
    status.hidden = true
  } catch {
    fail()
  }
})()
